# Generated by Django 4.0.5 on 2022-07-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('desciption', models.CharField(max_length=1000, null=True)),
                ('urlToImage', models.CharField(max_length=500, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('publishedAt', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='recent_category',
            field=models.CharField(default='general', max_length=200),
        ),
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapp.article')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapp.customer')),
            ],
        ),
    ]
